//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracOtopark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracOtopark()
        {
            this.Odeme = new HashSet<Odeme>();
        }
    
        public int AracOtoparkID { get; set; }
        public int AracID { get; set; }
        public int OtoparkID { get; set; }
        public Nullable<System.DateTime> GirisSaati { get; set; }
        public Nullable<System.DateTime> CikisSaati { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Otopark Otopark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odeme> Odeme { get; set; }
    }
}
