//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme
    {
        public int OdemeID { get; set; }
        public Nullable<int> OtoparkID { get; set; }
        public Nullable<int> Odeme1 { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual AracOtopark AracOtopark { get; set; }
    }
}
